---
name: C20s-Credits
version: 0.0.1
author: creeperplayer20
main: creeperplayer20\credits\Main
api: 5.3.2
src-namespace-prefix: creeperplayer20\credits

permissions:
  c20s-credits.use:
    description: Allows the user to use the /credits command
    default: true
  c20s-credits.check:
    description: Allows the user to check their or someone else's credits
    default: op
  c20s-credits.add:
    description: Allows the admin to add credits to a player
    default: op
  c20s-credits.reduce:
    description: Allows the admin to reduce credits from a player
    default: op
  c20s-credits.set:
    description: Allows the admin to set a player's credits
    default: op
  c20s-credits.reset:
    description: Allows the admin to reset a player's credits
    default: op
  c20s-credits.reload:
    description: Allows the admin to reload the plugin
    default: op
...
